
services:

    spam:
        build: 
            context: .
        volumes:
            -   ~/spam_store:/spam_store
        stdin_open: true # docker run -i
        tty: true        # docker run -t
        user: ${CURRENT_UID}
        restart: no
        logging:
            driver: "json-file"
            options:
                max-file: "5"
                max-size: "10m"
